### ISSUE TITLE
Cambiar checkedo de condiciones de posibles conecciones por una froma mas ordenadas (tuplas?)

### ISSUE THREAD

**Issue by Manuelsi** [goljavi/Unity-Editor-Project#25]
` if (_lastLeftClickedNode is StartNode && _lastRightClickedNode is DialogueNode
            || _lastLeftClickedNode is DialogueNode && _lastRightClickedNode is OptionNode
            || _lastLeftClickedNode is OptionNode && _lastRightClickedNode is DialogueNode
            || _lastLeftClickedNode is EndNode && _lastRightClickedNode is OptionNode)`
Este codigo se va a hacer muy complicado de extender a futuro. Preferiblemente, cada nodo va a tener una referencia interna (estatica) de con que nodos se va a poder conectar, o tener un diccionario o lista de tuplas para hacer agregar conecciones mas faciles. Este if terminaría siendo, por ejemplo:
`if(ValidConection (_lastLeftClickedNode, _lastRightClickedNode)){`

**Comment by NullRef-Arcana** [comment]
Resuelto hace rato. Cada nodo tiene un metodo para verificar si la transicion seria valida
